### ISSUE TITLE
npm run build not working on 1.10.0, 1.11.0 and 1.11.1 

### ISSUE THREAD

**Issue by rajibbasu11** [DivanteLtd/vue-storefront-api#430]
npm run build showing this error..

> vue-storefront-api@1.10.0 build /home/rajib/Desktop/rajib/project-Vue-Storefront/vue-storefront-api
> npm run -s build:code && npm run -s build:copy:graphql && npm run -s build:copy:schema

node_modules/globby/index.d.ts:6:14 - error TS1005: ';' expected.

6  	| readonly string[]
   	           ~~~~~~

node_modules/globby/index.d.ts:6:21 - error TS1011: An element access expression should take an argument.

6  	| readonly string[]
   	                  

node_modules/globby/index.d.ts:7:23 - error TS1005: ',' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                    ~~~~~~

node_modules/globby/index.d.ts:7:29 - error TS1005: ',' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                          ~

node_modules/globby/index.d.ts:7:30 - error TS1109: Expression expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                           ~

node_modules/globby/index.d.ts:7:31 - error TS1005: ':' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                            ~

node_modules/globby/index.d.ts:7:55 - error TS1005: ',' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                                                    ~~~~~~

node_modules/globby/index.d.ts:7:61 - error TS1005: ',' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                                                          ~

node_modules/globby/index.d.ts:7:62 - error TS1109: Expression expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                                                           ~

node_modules/globby/index.d.ts:7:63 - error TS1005: ':' expected.

7  	| {files?: readonly string[]; extensions?: readonly string[]};
   	                                                            ~

node_modules/globby/index.d.ts:51:30 - error TS1005: ';' expected.

51  	readonly ignore?: readonly string[];
    	                           ~~~~~~

node_modules/globby/index.d.ts:51:37 - error TS1011: An element access expression should take an argument.

51  	readonly ignore?: readonly string[];
    	                                  

node_modules/globby/index.d.ts:55:1 - error TS1128: Declaration or statement expected.

55 }
   ~

node_modules/globby/index.d.ts:104:31 - error TS1005: ',' expected.

104  	patterns: string | readonly string[],
     	                            ~~~~~~

node_modules/globby/index.d.ts:104:37 - error TS1005: ',' expected.

104  	patterns: string | readonly string[],
     	                                  ~

node_modules/globby/index.d.ts:118:31 - error TS1005: ',' expected.

118  	patterns: string | readonly string[],
     	                            ~~~~~~

node_modules/globby/index.d.ts:118:37 - error TS1005: ',' expected.

118  	patterns: string | readonly string[],
     	                                  ~

node_modules/globby/index.d.ts:143:31 - error TS1005: ',' expected.

143  	patterns: string | readonly string[],
     	                            ~~~~~~

node_modules/globby/index.d.ts:143:37 - error TS1005: ',' expected.

143  	patterns: string | readonly string[],
     	                                  ~

node_modules/globby/index.d.ts:155:31 - error TS1005: ',' expected.

155  	patterns: string | readonly string[],
     	                            ~~~~~~

node_modules/globby/index.d.ts:155:37 - error TS1005: ',' expected.

155  	patterns: string | readonly string[],
     	                                  ~

node_modules/globby/index.d.ts:169:31 - error TS1005: ',' expected.

169  	patterns: string | readonly string[],
     	                            ~~~~~~

node_modules/globby/index.d.ts:169:37 - error TS1005: ',' expected.

169  	patterns: string | readonly string[],
     	                                  ~


Found 23 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront-api@1.10.0 build: `npm run -s build:code && npm run -s build:copy:graphql && npm run -s build:copy:schema`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront-api@1.10.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rajib/.npm/_logs/2020-04-08T11_12_56_809Z-debug.log

**Comment by rajibbasu11** [comment]
Graphql version problem.

**Comment by gukandrew** [comment]
@rajibbasu11 why did you close without posting the reason of this issue? It would be interesting to know what part of code cause that behavior.
